import type { ComponentType } from 'react';
import type { IconProps } from '@phosphor-icons/react';
import {
  ArrowCounterClockwise,
  ArrowLeft,
  ArrowRight,
  At,
  Calendar,
  CaretLeft,
  Circle,
  Check,
  CheckCircle,
  ClockCounterClockwise,
  Detective,
  Envelope,
  Eye,
  EyeSlash,
  Fire,
  FloppyDisk,
  GearSix,
  GameController,
  House,
  Lock,
  MagnifyingGlass,
  MaskHappy,
  Minus,
  Palette,
  Pause,
  Pencil,
  PencilSimple,
  PersonArmsSpread,
  Play,
  Plus,
  PlusCircle,
  Question,
  RadioButton,
  TextAa,
  Timer,
  Trophy,
  Trash,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  Users,
  UsersThree,
  SealCheck,
  X,
} from '@phosphor-icons/react';

const ICONS: Record<string, ComponentType<IconProps>> = {
  abc: TextAa,
  add: Plus,
  add_circle: PlusCircle,
  alternate_email: At,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  calendar_month: Calendar,
  cancel: X,
  check: Check,
  check_circle: CheckCircle,
  charades: PersonArmsSpread,
  chevron_left: CaretLeft,
  close: X,
  dashboard: GameController,
  delete: Trash,
  draw: Pencil,
  edit: PencilSimple,
  emoji_people: PersonArmsSpread,
  emoji_events: Trophy,
  group: Users,
  group_off: UserMinus,
  groups: UsersThree,
  help: Question,
  history: ClockCounterClockwise,
  history_edu: ClockCounterClockwise,
  home: House,
  how_to_reg: UserCheck,
  local_fire_department: Fire,
  lock: Lock,
  mail: Envelope,
  mafia: MaskHappy,
  name_family: TextAa,
  pause: Pause,
  person: User,
  person_add: UserPlus,
  person_search: Detective,
  pictionary: Palette,
  play_arrow: Play,
  radio_button_checked: RadioButton,
  radio_button_unchecked: Circle,
  remove: Minus,
  replay: ArrowCounterClockwise,
  save: FloppyDisk,
  search: MagnifyingGlass,
  settings: GearSix,
  sports_esports: GameController,
  spy: Detective,
  theater_comedy: MaskHappy,
  timer: Timer,
  truth_or_dare: Fire,
  visibility: Eye,
  visibility_off: EyeSlash,
  verified: SealCheck,
};

export interface AppIconProps extends Omit<IconProps, 'name'> {
  name: string;
}

export default function Icon({ name, size = '1em', weight = 'regular', ...props }: AppIconProps) {
  const IconComponent = ICONS[name] ?? Question;
  return <IconComponent aria-hidden="true" focusable="false" size={size} weight={weight} {...props} />;
}
