# Generated by Django 6.0.6 on 2026-06-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='status',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='timer_duration',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='timer_elapsed',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='timer_started_at',
        ),
    ]
