# Generated by Django 6.0.6 on 2026-06-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_remove_gamesession_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, unique=True)),
                ('name_fa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpyGameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ROLE_REVEAL', 'Role Reveal'), ('IN_PROGRESS', 'In Progress'), ('VOTING', 'Voting'), ('SPY_GUESS', 'Spy Guess'), ('FINISHED', 'Finished')], default='CREATED', max_length=20)),
                ('spy_count', models.IntegerField()),
                ('timer_started_at', models.DateTimeField(blank=True, null=True)),
                ('timer_elapsed', models.IntegerField(default=0)),
                ('timer_duration', models.IntegerField(default=300)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='spy.location')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spy_state', to='games.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='SpyPlayerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_spy', models.BooleanField(default=False)),
                ('role_en', models.CharField(max_length=255)),
                ('role_fa', models.CharField(max_length=255)),
                ('role_revealed', models.BooleanField(default=False)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spy_detail', to='games.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spy_player_states', to='games.gamesession')),
            ],
        ),
    ]
